import { heroFoodImages } from "@/lib/food-visuals";

export type MealCategoryKey = "Breakfast" | "Lunch" | "Dinner" | "Meal prep" | "Healthy" | "Dessert";

export type MealItem = {
  id: string;
  category: MealCategoryKey;
  title: string;
  subtitle: string;
  minutes: number;
  kcal: number;
  image: string;
  ingredients: string[];
  priceHint: string;
};

export const mealCategories: MealCategoryKey[] = [
  "Breakfast",
  "Lunch",
  "Dinner",
  "Meal prep",
  "Healthy",
  "Dessert",
];

export const mealItems: MealItem[] = [
  {
    id: "plantain-egg-breakfast",
    category: "Breakfast",
    title: "Plantain Egg Bowl",
    subtitle: "Sweet plantain, soft eggs, peppers, and greens.",
    minutes: 18,
    kcal: 520,
    image: heroFoodImages.jollof,
    ingredients: [
      "Ripe plantain",
      "Eggs",
      "Red onion",
      "Green bell pepper",
      "Tomato",
      "Baby spinach",
      "Coconut oil",
      "Salt",
      "Black pepper",
      "Parmesan",
    ],
    priceHint: "$22-$35",
  },
  {
    id: "avocado-toast-tray",
    category: "Breakfast",
    title: "Avocado Toast Tray",
    subtitle: "Crisp toast, eggs, citrus avocado, and chili oil.",
    minutes: 14,
    kcal: 410,
    image: heroFoodImages.salad,
    ingredients: [
      "Avocado",
      "Eggs",
      "Sourdough",
      "Lime juice",
      "Cilantro",
      "Tomato",
      "Olive oil",
      "Cumin",
      "Salt",
      "Black pepper",
      "Chili flakes",
    ],
    priceHint: "$18-$28",
  },
  {
    id: "jollof-lunch-box",
    category: "Lunch",
    title: "Jollof Lunch Box",
    subtitle: "Tomato rice, chicken, slaw, and plantain.",
    minutes: 28,
    kcal: 690,
    image: heroFoodImages.jollof,
    ingredients: [
      "Long grain rice",
      "Chicken",
      "Plantain",
      "Tomatoes",
      "Tomato paste",
      "Red bell pepper",
      "Onion",
      "Garlic",
      "Ginger",
      "Curry powder",
      "Thyme",
      "Bay leaf",
      "Vegetable oil",
      "Chicken stock",
    ],
    priceHint: "$25-$42",
  },
  {
    id: "suya-chicken-wrap",
    category: "Lunch",
    title: "Suya Chicken Wrap",
    subtitle: "Peppery chicken, crunchy salad, and yogurt sauce.",
    minutes: 20,
    kcal: 540,
    image: heroFoodImages.platter,
    ingredients: [
      "Chicken",
      "Flatbread",
      "Suya spice",
      "Cabbage",
      "Carrot",
      "Red onion",
      "Tomato",
      "Cucumber",
      "Yogurt",
      "Lemon juice",
      "Garlic",
      "Peanut powder",
    ],
    priceHint: "$20-$34",
  },
  {
    id: "italian-hot-pizza",
    category: "Dinner",
    title: "Italian Hot Pizza",
    subtitle: "Crisp crust, pepperoni, basil, and hot honey.",
    minutes: 35,
    kcal: 760,
    image: heroFoodImages.pizza,
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Mozzarella",
      "Pepperoni",
      "Fresh basil",
      "Olive oil",
      "Parmesan",
      "Garlic",
      "Oregano",
      "Red pepper flakes",
    ],
    priceHint: "$32-$55",
  },
  {
    id: "spicy-ramen-noodle",
    category: "Dinner",
    title: "Spicy Ramen Noodle",
    subtitle: "Broth, noodles, egg, mushrooms, and greens.",
    minutes: 14,
    kcal: 440,
    image: heroFoodImages.pasta,
    ingredients: [
      "Ramen noodles",
      "Egg",
      "Mushrooms",
      "Greens",
      "Chicken or vegetable broth",
      "Soy sauce",
      "Miso paste",
      "Garlic",
      "Ginger",
      "Chili oil",
      "Scallions",
      "Sesame oil",
    ],
    priceHint: "$24-$40",
  },
  {
    id: "weekly-protein-prep",
    category: "Meal prep",
    title: "Weekly Protein Prep",
    subtitle: "Chicken, grains, vegetables, and clean sauces.",
    minutes: 55,
    kcal: 610,
    image: heroFoodImages.salad,
    ingredients: [
      "Chicken breast",
      "Quinoa",
      "Broccoli",
      "Cherry tomatoes",
      "Avocado",
      "Olive oil",
      "Lemon juice",
      "Garlic",
      "Oregano",
      "Feta",
      "Salt",
      "Black pepper",
    ],
    priceHint: "$85-$150",
  },
  {
    id: "family-stew-pack",
    category: "Meal prep",
    title: "Family Stew Pack",
    subtitle: "A rich stew base, rice, protein, and sides.",
    minutes: 70,
    kcal: 700,
    image: heroFoodImages.platter,
    ingredients: [
      "Stewing beef",
      "Rice",
      "Onion",
      "Carrot",
      "Celery",
      "Tomato paste",
      "Beef stock",
      "Thyme",
      "Bay leaf",
      "Worcestershire sauce",
      "Vegetable oil",
      "Parsley",
    ],
    priceHint: "$95-$180",
  },
  {
    id: "green-gym-bowl",
    category: "Healthy",
    title: "Green Gym Bowl",
    subtitle: "Lean protein, greens, avocado, and citrus dressing.",
    minutes: 22,
    kcal: 480,
    image: heroFoodImages.salad,
    ingredients: [
      "Turkey",
      "Mixed greens",
      "Avocado",
      "Brown rice",
      "Cucumber",
      "Cherry tomatoes",
      "Lemon juice",
      "Olive oil",
      "Garlic",
      "Dijon mustard",
      "Pumpkin seeds",
      "Black pepper",
    ],
    priceHint: "$24-$38",
  },
  {
    id: "salmon-veg-plate",
    category: "Healthy",
    title: "Salmon Veg Plate",
    subtitle: "Seared salmon, vegetables, herbs, and rice.",
    minutes: 26,
    kcal: 560,
    image: heroFoodImages.platter,
    ingredients: [
      "Salmon",
      "Rice",
      "Asparagus",
      "Lemon",
      "Garlic",
      "Olive oil",
      "Parsley",
      "Dill",
      "Cherry tomatoes",
      "Salt",
      "Black pepper",
    ],
    priceHint: "$34-$58",
  },
  {
    id: "berry-cream-cake",
    category: "Dessert",
    title: "Berry Cream Cake",
    subtitle: "Soft cake, cream, berries, and vanilla.",
    minutes: 45,
    kcal: 390,
    image: heroFoodImages.dessert,
    ingredients: [
      "Vanilla sponge",
      "Mixed berries",
      "Heavy cream",
      "Mascarpone",
      "Vanilla extract",
      "Sugar",
      "Lemon juice",
      "Eggs",
      "Flour",
      "Baking powder",
      "Butter",
    ],
    priceHint: "$36-$70",
  },
  {
    id: "warm-cookie-box",
    category: "Dessert",
    title: "Warm Cookie Box",
    subtitle: "Fresh cookies, chocolate, and sea salt.",
    minutes: 25,
    kcal: 330,
    image: heroFoodImages.dessert,
    ingredients: [
      "All-purpose flour",
      "Chocolate chips",
      "Butter",
      "Brown sugar",
      "Granulated sugar",
      "Egg",
      "Vanilla extract",
      "Baking soda",
      "Baking powder",
      "Kosher salt",
      "Flaky sea salt",
    ],
    priceHint: "$20-$45",
  },
];

export function getMealItemById(id?: string) {
  return mealItems.find((item) => item.id === id) ?? null;
}

export function getMealItemsByCategory(category?: string) {
  if (!category) {
    return mealItems;
  }

  const normalized = category.toLowerCase();
  return mealItems.filter((item) => item.category.toLowerCase() === normalized);
}

export const globalServiceAreas = [
  "New York, United States",
  "Los Angeles, United States",
  "Chicago, United States",
  "Houston, United States",
  "Atlanta, United States",
  "Toronto, Canada",
  "Vancouver, Canada",
  "London, United Kingdom",
  "Manchester, United Kingdom",
  "Birmingham, United Kingdom",
  "Lagos, Nigeria",
  "Abuja, Nigeria",
  "Accra, Ghana",
  "Nairobi, Kenya",
  "Johannesburg, South Africa",
  "Cape Town, South Africa",
  "Dubai, United Arab Emirates",
  "Doha, Qatar",
  "Paris, France",
  "Berlin, Germany",
  "Amsterdam, Netherlands",
  "Madrid, Spain",
  "Rome, Italy",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Singapore",
  "Tokyo, Japan",
  "Seoul, South Korea",
  "Mumbai, India",
  "Delhi, India",
  "Mexico City, Mexico",
  "Sao Paulo, Brazil",
  "Buenos Aires, Argentina",
];
